---
- name: Prepare Container - add SSH and configure user
  hosts: all
  gather_facts: true
  
  # here we use the vault_password for user configuration,
  # there is no need to define the vault in the molecule.yml 
  # as its only required for some tasks inside her - 
  # in ubuntu26_ssh its different, we need the password throughout all playbooks
  # there are options to make it more locally - inside tasks 
  # but the maintanence effort is too high, just keep it here
  vars_files:
    - "{{ playbook_dir }}/../../group_vars/all/test_setup_vault.yml"
  tasks:

    - name: Verify if password exists
      ansible.builtin.debug:
        msg: >
          {% if vault_ubuntu_password is defined and vault_ubuntu_password | length > 0 %}
          Password loaded and available
          {% else %}
          WARNING: Password is missing or empty!
          {% endif %}

    - name: Install OpenSSH Server and testing utilities
      ansible.builtin.apt:
        name:
          - openssh-server
          - time
          - sudo
        state: present
        update_cache: true

    - name: Enable password authentication in sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present

    - name: Set temporary password for the existing ubuntu user
      ansible.builtin.user:
        name: ubuntu
        password: "{{ vault_ubuntu_password | ansible.builtin.password_hash('sha512') }}"

    - name: Ensure ubuntu user has passwordless sudo privileges
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ubuntu
        line: 'ubuntu ALL=(ALL) NOPASSWD:ALL'
        state: present
        mode: '0440'
        create: true

    - name: Force restart of SSH service to apply config
      ansible.builtin.service:
        name: ssh
        state: restarted

