---
- name: Prepare Container - add SSH and configure user
  hosts: all
  gather_facts: true
  tasks:
    - name: Install OpenSSH Server and testing utilities
      ansible.builtin.apt:
        name:
          - openssh-server
          - time
          - sudo
        state: present
        update_cache: true

    - name: Enable password authentication in sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present

    - name: Set temporary password for the existing ubuntu user
      ansible.builtin.user:
        name: ubuntu
        # Password is 'ansible' (hashed using SHA-512)
        password: "{{ 'ansible' | ansible.builtin.password_hash('sha512') }}"
        # "$6$rounds=656000$hNleW7CqJzZp$vB0E4j/S0k6tL807r9LgB9.5C6A3dF1FfQyXnLgqRmW/m8M7pC4Q0h9vXW5bF8I7ZgW2s5L3bL3bL3bL3bL3bZ."
        # "$6$rounds=656000$hNleW7CqJzZp$vB0E4j/S0k6tL807r9LgB9.5C6A3dF1FfQyXnLgqRmW/m8M7pC4Q0h9vXW5bF8I7ZgW2s5L3bL3bL3bL3bL3b."
                  
    - name: Ensure ubuntu user has passwordless sudo privileges
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ubuntu
        line: 'ubuntu ALL=(ALL) NOPASSWD:ALL'
        state: present
        mode: '0440'
        create: true

    - name: Force restart of SSH service to apply config
      ansible.builtin.service:
        name: ssh
        state: restarted

