---
driver:
  name: docker
platforms:
  - name: ubuntu-twin
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
    cgroupns: host
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "$MOLECULE_EPHEMERAL_DIRECTORY/roles:$MOLECULE_PROJECT_DIRECTORY/roles:../../roles"
    ANSIBLE_CALLBACK_RESULT_FORMAT: "yaml"
    ANSIBLE_DISPLAY_FAILED_STDERR: "true"
    demo_detailed: "{{ lookup('env', 'DEMO_DETAILED') | default('false', true) }}"
  config:
    timeout: 120
    inventory:
      defaults:
        ansible_python_interpreter: ansible-posix.get_env PATH python
        ansible_connection: ssh
        ansible_user: ubuntu
        ansible_become: true
        ansible_become_method: sudo
      groups:
        all:
          docker_host_ip: '172.17.0.1'
          ansible_user: ubuntu
          ansible_become: true
          ansible_become_method: sudo
  
  ansible_args:
    - --extra-vars
    - "demo_detailed_raw={{ lookup('env', 'DEMO_DETAILED') | default('false', true) }}"

verifier:
  name: ansible
