---

# Since Molecule v6 (`driver: default`), Molecule adopts the "native-ansible" architecture. 
# Attempting to enforce connection variables—such as `ansible_host: 127.0.0.1` or `ansible_port: 2222`—inside `molecule.yml`
# under the `provisioner.inventory` key fail very often and turned out to be very unreliable.
# Molecule ignores these values during the generation of its temporary ephemeral cache or overrides them with an empty object (`{}`).
# Consequently, Ansible tries to resolve the hostname (e.g., `ubuntu26-sandbox`) directly via DNS,
# resulting in a `Temporary failure in name resolution` error in case of docker.
# The solution, aligned with the official Ansible standard, is to offload these definitions into a separate `hosts.yml` inventory file. 
# This bypasses Molecule's restrictive internal inventory generation. 
# Ansible reads this inventory file directly, immediately recognizes the IP `127.0.0.1` and port `2222`,#
# and applies them from the very first millisecond (including during the initial `Fact Gathering` phase).

all:
  children:
    # Hier definierst du deine Test-Gruppe
    sandbox_nodes:
      hosts:
        ubuntu26-sandbox:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_connection: ssh
          ansible_user: ubuntu
          ansible_password: "{{ vault_ubuntu_password }}"
          ansible_python_interpreter: auto_silent
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR'
