---
# molecule/ubuntu26_ssh/molecule.yml
dependency:
  name: galaxy
  enabled: false
driver:
  name: default
ansible:
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        # Key fix: Enforces native Ansible inventory handling and bypasses molecule.yml overrides
        - --inventory=hosts.yml
        # defines the all.yml, where the ssh key file is defined
        - --extra-vars=@${MOLECULE_PROJECT_DIRECTORY}/group_vars/all/all.yml
        # defines the path to the password file.
        # @ : defines a path for ansible, otherwise it would be a k:v
        - --extra-vars=@${MOLECULE_PROJECT_DIRECTORY}/group_vars/all/test_setup_vault.yml
  env:
    ANSIBLE_CALLBACK_RESULT_FORMAT: yaml
    ANSIBLE_DISPLAY_FAILED_STDERR: 'true'
    ANSIBLE_INTERPRETER_PYTHON: auto_silent
    ANSIBLE_REMOTE_TMP: /tmp
    ANSIBLE_CONFIG: "${MOLECULE_PROJECT_DIRECTORY}/ansible.cfg"
    ANSIBLE_VAULT_PASSWORD_FILE: "${MOLECULE_PROJECT_DIRECTORY}/../.vault_pass"

platforms:
  - name: ubuntu26-sandbox
